server:
  port: 8030
  #应用名称( nacos会将该名称当做服务名称)
spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 192.168.10.11:8847
      discovery:
        username: nacos
        password: nacos
        namespace: public
stock-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.tulingxueyuan.ribbon.rule.CustomRule
ribbon:
  eager-load:
   #开启ribbon饥饿加载
    enable: true
    #配置mall-user使用ribbon饥饿加载，多个使用逗号分隔
    clients: stock-service